### ISSUE TITLE
no primary events on iOS

### ISSUE THREAD

**Issue by robx** [mpizenberg/elm-pep#4]
This was initially reported to the demo project: https://github.com/mpizenberg/demo-elm-image-annotation/issues/1. I've since narrowed the issue down a bit.

Serving the code at https://ellie-app.com/993kLCWvga1/0 locally and testing with iOS, it turns out that `touch.identifier` is a "random" large integer, so the primary detection based on `identifer == 0` does not work.

It seems that to do this correctly, it would be necessary to keep some state. (E.g. for a sequence finger-1-down finger-2-down finger-1-up finger-2-up.)

**Comment by robx** [comment]
I'm not that sure of my diagnostic anymore, compare PR #5. It seems that the missing `movement{X,Y}` is the more immediate bug.

**Comment by mpizenberg** [comment]
Ok thanks, I will continue conversation in PR #5.
